server:
  port: 8090

spring:
  # 系统使用的环境
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


logging:
  level:
    root: info
    org.hibernate: info
    org.springframework.amqp: info
    # 显示 sql 语句的参数
    org.hibernate.type.descriptor.sql.BasicBinder: info
    org.hibernate.type.descriptor.sql.BasicExtractor: info
    # 应用日志级别
    com.shiro: debug
